export const SITE = {
  name: 'Orcazo',
  domain: 'orcazo.com',
  inboundDomain: 'orcazo.com',
  tagline: 'The supreme platform for affiliate content marketing',
  description: 'The supreme platform for affiliate content marketing. Empowering creators worldwide.',
  keywords: [
    'Orcazo',
    'affiliate content marketing',
    'get paid to post videos',
    'creator payouts',
    'short-form content campaigns',
    'UGC creator network',
    'make money on TikTok',
    'make money on Instagram',
    'paid video campaigns',
    'creator monetization',
  ],
  url: 'https://www.orcazo.com',
} as const;
